const initialPosts=[
 {title:'How to Choose the Right Floor Tiles for Your House',date:'2026-09-14',category:'Tiles',excerpt:'A practical checklist for choosing floor tiles based on room, traffic, maintenance and the look you want.',image:'assets/tile-01.jpeg',path:'content/blog/01-choose-floor-tiles.md'},
 {title:'Plain vs Coloured Cabro: Which Should You Choose?',date:'2026-09-14',category:'Cabro & Paving',excerpt:'The practical differences between plain and coloured cabro — and what to consider before paving your compound.',image:'assets/cabro-2.jpg',path:'content/blog/02-plain-vs-coloured-cabro.md'},
 {title:'5 Things to Check Before Buying a Door',date:'2026-09-14',category:'Doors',excerpt:'Avoid an expensive mismatch by checking size, swing, frame, finish and hardware before you buy.',image:'assets/door-03.jpeg',path:'content/blog/03-before-you-buy-a-door.md'}
];
let posts=[...initialPosts]; let active='All';
const grid=document.getElementById('journalGrid'), filter=document.getElementById('journalFilter');
function card(p,i){return `<article class="journal-card"><a href="article.html?path=${encodeURIComponent(p.path)}"><div class="journal-image"><img src="${p.image||'assets/storefront.jpg'}" alt="${PeakContent.escapeHtml(p.title)}" loading="lazy"></div><div class="journal-body"><div class="product-cat">${PeakContent.escapeHtml(p.category||'Advice')}</div><h3>${PeakContent.escapeHtml(p.title)}</h3><p>${PeakContent.escapeHtml(p.excerpt||'Practical advice from Peak Legacy Hardware.')}</p><div class="journal-meta">${p.date||''}<span>Read article →</span></div></div></a></article>`}
function render(){const visible=posts.filter(p=>active==='All'||p.category===active);grid.innerHTML=visible.map(card).join('')||'<div class="empty"><h3>No articles in this category yet.</h3></div>';}
function renderFilters(){const cats=['All',...new Set(posts.map(p=>p.category).filter(Boolean))];filter.innerHTML=cats.map(c=>`<button class="filter ${c===active?'active':''}">${c}</button>`).join('');filter.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.textContent;renderFilters();render();});}
(async()=>{try{const remote=await PeakContent.loadFolder('content/blog');const published=remote.filter(p=>String(p.published).toLowerCase()!=='false');if(published.length)posts=published.map(p=>({...p,image:p.image||'assets/storefront.jpg'})).sort((a,b)=>String(b.date).localeCompare(String(a.date)));}catch(e){console.info('Using built-in article fallback.');}renderFilters();render();})();
const menuBtn=document.getElementById('menuBtn'),nav=document.getElementById('nav');menuBtn.onclick=()=>{const open=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)};
